---
title: "R Notebook"
output: html_notebook
---

```{r}
d <- read_csv("/Users/lucmekouar/Desktop/POLI 3148/!!POLI_3148_repo/data-1984_2022/vdem_1984_2022_external.csv")
 
```

```{r}
names(d)
```

```{r}
d |> select(country_name, country_id, year)
```

```{r}
d |> select(country_name, country_id, year) |> distinct()
```

```{r}
d |> select(country_name) |> distinct()
```

```{r}
d_gdp <- d |> 
  select(country_name, country_id, year, e_gdp, e_gdppc)


```

```{r}
d_gdp <- d_gdp |> 
  rename("GDP" = "e_gdp", "GDP per capita" = "e_gdppc", "country" = "country_name", "ID" = "country_id", "Year" = "year")
```

```{r}
d_gdp
```

```{r}
d_gdp |> 
  slice_max(order_by = GDP, n = 10)
```

```{r}
d_gdp |> slice_min(order_by = GDP, n = 10)
```

```{r}
set.seed(52)
d_gdp |> slice_sample(n = 10)
```

```{r}
set.seed(52)
d_gdp |> slice_sample(prop = 01)
```

```{r}
# want 2000-2005

d_gdp |> 
  filter(Year >= 2000 & Year <= 2005)
```

```{r}
d_gdp |> filter(country == "China")
```

```{r}
d_gdp |> filter(country == "China") |> filter(Year >= 2000 & Year <= 2005)
```

```{r}
# sort rows by GDP per capita non decreasing
d_gdp |> arrange(`GDP per capita`)
```

```{r}
#
d_gdp |> 
  group_by(country) |>
  slice_max(GDP,n = 1)

```

```{r}
# how many entries are there for each country
d_gdp |> 
  group_by(country) |>
  count()
  
```

```{r}

d_gdp |>
  group_by(country) |>
  slice_min(order_by = GDP , n = 1)


```

```{r}
d_gdp |> mutate(New = log(GDP)+1)

d_gdp |>
  mutate(GDP_AVG = GDP / mean(GDP, na.rm = TRUE))
```

```{r}
d_gdp |>
  filter(country == "China", Year == 2001) |>
  mutate(GDP_AVG = GDP / mean(GDP, na.rm = TRUE))

```

```{r}
d_gdp |>
  group_by(country) |>
  arrange(Year) |>
  mutate(GDP_over_1984 = GDP / first(GDP)) |>
  ungroup() |>
  arrange(country, Year) 

```

```{r}
d_gdp |>
  group_by(country) |>
  arrange(Year) |>
  mutate(GDP_yoy_change = GDP - lag(GDP, n = 1)) |>
  ungroup() |>
  arrange(country, Year) 

```

```{r}
d_gdp |>
  summarise(gdp_average = mean(GDP, na.rm = TRUE))

```

```{r}
d_gdp |>
  group_by(country) |>
  summarise(GDP_average = mean(GDP,na.rm = TRUE), 
            GDPpc_average = mean(`GDP per capita`,na.rm = TRUE))
          
```

```{r}
d_gdp |>
  filter(Year >= 1984 & Year <= 2020) |>
  group_by(country) |>
  arrange(Year) |>
  summarise(GDP_growth_2020_1984 = (last(GDP) - first(GDP) / first(GDP)),
            GDPpc_growth_2020_1984 = (last(`GDP per capita`) - first(`GDP per capita`) / first(`GDP per capita`))) |>
  ungroup() |>
  arrange(country)

?summarise
```

```{r}
#integrity check

d_gdp |>
  mutate(GDP_missing = is.na(GDP), .after = GDP) |>
  group_by(country) |>
  summarise(N_GDP_missing = sum(GDP_missing)) |>
  arrange(-N_GDP_missing)


```
